SystemOrganization addCategory: #'GraphQL-Core'!
SystemOrganization addCategory: 'GraphQL-Core-Builder'!
SystemOrganization addCategory: 'GraphQL-Core-Execution'!
SystemOrganization addCategory: 'GraphQL-Core-Introspection'!
SystemOrganization addCategory: 'GraphQL-Core-Models'!
SystemOrganization addCategory: 'GraphQL-Core-Parsing'!
SystemOrganization addCategory: 'GraphQL-Core-Resolvers'!
SystemOrganization addCategory: 'GraphQL-Core-Utilities'!
